=== allin58/JavaWebDev/task4/src/candyschema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">




    <xs:element name="candies" >

        <xs:complexType>
            <xs:sequence>
                <xs:element name="candy" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="energy" type="xs:string"/>


                            <xs:element name="type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="caramel"/>
                                        <xs:enumeration value="chocolate"/>
                                        <xs:enumeration value="chocolate with stuffing"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>


                            <xs:element name="value">
                                <xs:complexType>
                                    <xs:sequence>
                                       <xs:element name="proteins" type="xs:string"/>
                                       <xs:element name="fats" type="xs:string"/>
                                       <xs:element name="carbohydrates" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="production" type="xs:string"/>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>




    </xs:element>
</xs:schema>

=== allin58/JavaWebDev/task4/src/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="candyschema.xsd">



  <candy>
      <name>alpen Gold</name>
      <energy>500</energy>
      <type>chocolate</type>


      <value>
          <proteins>15</proteins>
          <fats>20</fats>
          <carbohydrates>7</carbohydrates>
      </value>
      <production>proizvoditel</production>
  </candy>




  <candy>
      <name>sdf</name>
      <energy>fgh</energy>

      <type>caramel</type>
      <value>
          <proteins>2</proteins>
          <fats>2</fats>
          <carbohydrates>2</carbohydrates>
      </value>
      <production>fgh</production>
  </candy>





</candies>
